### ISSUE TITLE
Docker Container stops after error AttributeError: 'NoneType' object has no attribute 'exc_info'

### ISSUE THREAD

**Issue by varveler** [benoitc/gunicorn#1498]
I get the following error every once in a while (like every two weeks) for no apparent reasons, is similar to #1120. Running Gunicorn 19.6.0 and Nginx using Docker + Docker Compose in a DigitalOcean droplet  with CoreOs 1235.9 with 512MB in memory.  I'm relative new to web development I would appreciate any help. These are my container logs:

```
jsb_web  | [2017-04-10 11:28:21 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:216)
jsb_web  | [2017-04-10 11:29:10 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:226)
jsb_web  | [2017-04-10 06:29:11 +0000] [226] [INFO] Worker exiting (pid: 226)
jsb_web  | [2017-04-10 06:29:11 +0000] [216] [INFO] Worker exiting (pid: 216)
jsb_web  | Unhandled exception in thread started by <bound method Reloader.__bootstrap of <Reloader(Thread-1, stopped daemon 139766190769920)>>
jsb_web  | Traceback (most recent call last):
jsb_web  |   File "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap
jsb_web  |     self.__bootstrap_inner()
jsb_web  |   File "/usr/local/lib/python2.7/threading.py", line 814, in __bootstrap_inner
jsb_web  |     (self.name, _format_exc()))
jsb_web  |   File "/usr/local/lib/python2.7/traceback.py", line 241, in format_exc
jsb_web  |     etype, value, tb = sys.exc_info()
jsb_web  | AttributeError: 'NoneType' object has no attribute 'exc_info'
```

Gunicorn is started via de Docker Compose File Command:
```
/usr/local/bin/gunicorn JSB3.wsgi:application -w 2 -b :8000 --reload
```

Docker Compose File is:

```
version: '2'
services:
  db:
      build: ./docker/postgis
      command: sh -c "echo \"host all all 0.0.0.0/0 md5\" >> /etc/postgresql/9.5/main/pg_hba.conf && /start-postgis.sh"
      container_name: jsb_db
      hostname: jsb_db
      env_file: docker/postgis/.env
      volumes:
          - db_data:/var/lib/postgresql/
          - ./docker/postgis/db_backups:/db_backups

  web:
      restart: always
      build: ./code
      command: /usr/local/bin/gunicorn JSB3.wsgi:application -w 2 -b :8000 --reload
      container_name: jsb_web
      hostname: jsb_web
      volumes:
          - ./code/:/code/
      ports:
          - "8000:8000"
      links:
          - db
      env_file: .env
      depends_on:
          - db

  nginx:
      restart: always
      build: ./docker/nginx/
      container_name: jsb_nginx
      hostname: jsb_nginx
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - /www/static
          - ./docker/nginx/certs:/etc/letsencrypt/
      volumes_from:
          - web
      links:
          - web:web

volumes:
  db_data:
```

Thanks!
