### ISSUE TITLE
Gunicorn running in Docker container with docker-compose

### ISSUE THREAD

**Issue by andrewgy8** [benoitc/gunicorn#1533]
The other day I created a standalone docker container with Gunicorn serving a Flask app. Everything worked fine.

Yesterday, I created a docker-compose file to run all the containers including Nginx and now the same command fails to start the Gunicorn process properly.  I cant even serve the application directly when I expose the Gunicorn port 8000.

Here is the docker-compose.yml:
```
version: '2'
 
services:
  web:
    restart: always
    build: ./web_app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./web_app:/data/web
    command: /usr/local/bin/gunicorn web_interface:app -w 4 -t 90 --log-level=debug -b 0.0.0.0:8000 --reload
    depends_on:
      - postgres
 
  nginx:
    restart: always
    build: ./nginx
    ports:
     - "8080:80"
    volumes_from:
      - web
    depends_on:
      - web
 
  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    expose:
      - "5432"

  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    tty: true
```

The errors I get in my terminal are 
<img width="793" alt="screen shot 2017-06-21 at 1 53 49 pm" src="https://user-images.githubusercontent.com/14836934/27387522-3d36dba0-5699-11e7-8a48-7218b145e50e.png">

Any idea why this might be happening? 

When I navigate to localhost:8000 I get nothing rendered. And then when i navigate to localhost:8080 I get a 504 error.  

Thanks for the help!
