### ISSUE TITLE
No app logging using nginx and gunicorn

### ISSUE THREAD

**Issue by holic-cl** [benoitc/gunicorn#2375]
Hi,

I am deploying an python application using Nginx web server and Gunicorn. I setup gunicorn to run as systemd process on my server.

Everything is working well except print logs from my app on errorlog. My logfile only is showing GET, POST; etc methods (I think this logs are made by Nginx). Nonetheless something weird happen spontaneously, it seems to make a dump of every logs captured that have been made.

Here is my configuration:
```
  config: None
  bind: ['unix:/home/admin/run/gunicorn-dispatch.socket']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 600
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/admin/webapps/collahuasi-dispatch-params-mockup
  daemon: False
  raw_env: []
  pidfile: /home/admin/run/gunicorn/dispatch-pid
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/admin/logs/dispatch-access.log
  disable_redirect_access_to_syslog: True
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/admin/logs/dispatch-error.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f221c1c2950>
  on_reload: <function OnReload.on_reload at 0x7f221c1c2a60>
  when_ready: <function WhenReady.when_ready at 0x7f221c1c2b70>
  pre_fork: <function Prefork.pre_fork at 0x7f221c1c2c80>
  post_fork: <function Postfork.post_fork at 0x7f221c1c2d90>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f221c1c2ea0>
  worker_int: <function WorkerInt.worker_int at 0x7f221c1d6048>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f221c1d6158>
  pre_exec: <function PreExec.pre_exec at 0x7f221c1d6268>
  pre_request: <function PreRequest.pre_request at 0x7f221c1d6378>
  post_request: <function PostRequest.post_request at 0x7f221c1d6400>
  child_exit: <function ChildExit.child_exit at 0x7f221c1d6510>
  worker_exit: <function WorkerExit.worker_exit at 0x7f221c1d6620>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f221c1d6730>
  on_exit: <function OnExit.on_exit at 0x7f221c1d6840>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
```

Any clue if you can help?, thanks!
Regards
