### ISSUE TITLE
Undetected Chrome Driver Randomly Causing Thread Exit

### ISSUE THREAD

**Issue by SocialRealm** [benoitc/gunicorn#2892]
Since my first design of this bot a year ago, I've had this issue and I'm stuck finding a solution because I'm not advanced enough at python, so hopefully, someone can help.

I have a cron job that calls my API to spin up a thread to run "checkStatus".  This code has one function: to interact with a website that processes paperwork.  It uses the undetected_chrome driver, which is apparently causing issues with my gunicorn events.  

Randomly, my thread will:   (gevent output log) 
```
[79267] [INFO] Parent changed, shutting down: <Worker 3633>
[79267] [INFO] Worker exiting (pid: 3633)
```

This occurs at a single line in my code:
`driver = uc.Chrome(version_main=106, options=options, service_log_path=slPath,headless=hdl)`

If anybody has any ideas as to why the driver initialization is causing the thread parent to change, I'd really appreciate your help!

Here is my config:
```
Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:4170']
  backlog: 2048
  workers: 3
  worker_class: gevent
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 0
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1001
  group: 1001
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/etr/Decepticons/BOTRepo/data/mmcSystem/logs/mmcBotLogs/geventSTDOUT.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/etr/Decepticons/BOTRepo/data/mmcSystem/logs/mmcBotLogs/geventSTDERR.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: gunicorn
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7feed982d670>
  on_reload: <function OnReload.on_reload at 0x7feed982d790>
  when_ready: <function WhenReady.when_ready at 0x7feed982d8b0>
  pre_fork: <function Prefork.pre_fork at 0x7feed982d9d0>
  post_fork: <function Postfork.post_fork at 0x7feed982daf0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7feed982dc10>
  worker_int: <function WorkerInt.worker_int at 0x7feed982dd30>
  worker_abort: <function WorkerAbort.worker_abort at 0x7feed982de50>
  pre_exec: <function PreExec.pre_exec at 0x7feed982df70>
  pre_request: <function PreRequest.pre_request at 0x7feed98410d0>
  post_request: <function PostRequest.post_request at 0x7feed9841160>
  child_exit: <function ChildExit.child_exit at 0x7feed9841280>
  worker_exit: <function WorkerExit.worker_exit at 0x7feed98413a0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7feed98414c0>
  on_exit: <function OnExit.on_exit at 0x7feed98415e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
```
