### ISSUE TITLE
--reload not working for docker

### ISSUE THREAD

**Issue by ArturHarutunyan** [benoitc/gunicorn#3135]
I have a Docker setup running Gunicorn with Uvicorn workers. It's configured to reload on file changes. However, it starts reloading when settings.py is modified but never completes the process.

**Docker Configuration:**
```
  actions:
    restart: always
    build:
      context: ./services/actions
      shm_size: '512mb'
    shm_size: '512mb'
    ports:
      - 8082:8080
    volumes:
      - ./services/actions/logs:/app/logs
      - ./services/actions/src:/app/src
      - ./services/actions/api.py:/app/api.py
    env_file:
      - .env
      - .local.env
    command: gunicorn api:app --workers $ACTION_WORKERS_COUNT --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$ACTION_PORT --timeout 600 --log-level debug --max-requests 0 --reload --reload-engine=inotify
```
**Logs**
```
[2023-12-29 10:51:56 +0000] [424] [INFO] Worker reloading: settings.py modified
[2023-12-29 10:51:56 +0000] [422] [INFO] Worker reloading: settings.py modified
[2023-12-29 10:51:56 +0000] [423] [INFO] Worker reloading: settings.py modified
[2023-12-29 10:51:56 +0000] [421] [INFO] Worker reloading: settings.py modified
```
Any insights on why the reloading process isn't completing would be greatly appreciated.
