### ISSUE TITLE
Why can a single worker process use multiple cores in a k8s environment? 

### ISSUE THREAD

**Issue by fighterhit** [benoitc/gunicorn#3150]
Why can a single worker process use multiple cores in a k8s environment? According to my understanding, one python process can only use one core?

I test the program using the following config in k8s cluster:

```
# my pod command
gunicorn --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --keep-alive 60 main:app
```

```
# pod resource yaml

resources:
  limits:
    cpu: "3"
    memory: 8Gi
  requests:
    cpu: "3"
    memory: 8Gi
```

```
# cat /sys/fs/cgroup/cpuset/cpuset.cpus 
11,58-59
```

![1gunicorn-cpu](https://github.com/benoitc/gunicorn/assets/23624910/b3967e2c-39af-447f-a1e8-75b95ecb6346)
